name: Test CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash ./.github/scripts/release.sh
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
