name: Test CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:

jobs:
  
  # Ubuntu
  build-arduino-linux:
    name: Arduino ${{ matrix.chunk }} on ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Sketches
      run: bash ./tools/ci/on-push.sh ${{ matrix.chunk }} 15

  # Windows and MacOS
  build-arduino-win-mac:
    name: Arduino on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Sketches
      run: bash ./tools/ci/on-push.sh 1 30

  # PlatformIO on Windows, Ubuntu and Mac
  build-platformio:
    name: PlatformIO on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Sketches
      run: bash ./tools/ci/on-push.sh 1 1
      
      
#   build:
#     name: Build ${{ matrix.chunk }} on ${{ matrix.os }}
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macOS-latest]
#         chunk: [0, 1, 2, 3, 4, 5]
#     steps:
#     - uses: actions/checkout@v1
#     - name: Build
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         CHUNK_INDEX: ${{ matrix.chunk }}
#         CHUNKS_CNT: 6
#       run: bash ./.github/scripts/push.sh
#     - name: Upload build artifacts
#       uses: actions/upload-artifact@v1
#       with:
#         name: artifacts
#         path: build
