name: Test CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:

jobs:

  build-arduino-linux:
    name: Arduino ${{ matrix.chunk }} on ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Sketches
      run: bash ./tools/ci/on-push.sh ${{ matrix.chunk }} 12

  build-arduino-mac:
    name: Arduino ${{ matrix.chunk }} on macOS-latest
    runs-on: macOS-latest
    strategy:
      matrix:
        chunk: [3, 6]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Sketches
      run: bash ./tools/ci/on-push.sh ${{ matrix.chunk }} 12

  build-arduino-win:
    name: Arduino ${{ matrix.chunk }} on windows-latest
    runs-on: windows-latest
    strategy:
      matrix:
        chunk: [5, 15, 25]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Sketches
      run: bash ./tools/ci/on-push.sh ${{ matrix.chunk }} 30

  build-platformio:
    name: PlatformIO on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Sketches
      run: bash ./tools/ci/on-push.sh 1 1
      
      
#   build:
#     name: Build ${{ matrix.chunk }} on ${{ matrix.os }}
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macOS-latest]
#         chunk: [0, 1, 2, 3, 4, 5]
#     steps:
#     - uses: actions/checkout@v1
#     - name: Build
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         CHUNK_INDEX: ${{ matrix.chunk }}
#         CHUNKS_CNT: 6
#       run: bash ./.github/scripts/push.sh
#     - name: Upload build artifacts
#       uses: actions/upload-artifact@v1
#       with:
#         name: artifacts
#         path: build
