name: Test CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash ./.github/scripts/push.sh
    #- name: Upload build artifacts
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: artifacts
    #    path: build
