name: Test CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:

jobs:

  # Default
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Sketches
      run: bash ./.github/scripts/push.sh
