name: Publish

on:
  release:
    types: published

jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build
      run: cat $GITHUB_EVENT_PATH
