name: Publish

on: release

jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build
      run: echo should be building
    - name: Upload files to release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'folder1/*'
