name: Publish

on:
  release:
    types: published

jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build Release
      run: sudo apt-get install -y ca-certificates curl jq
    - name: Build Release
      run: env && cat $GITHUB_EVENT_PATH
