name: Test Event

on: repository_dispatch

jobs:
  run:
    name: Event on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
#     - uses: actions/checkout@v1
    - name: Install Arduino IDE
      uses: me-no-dev/arduino-ide-action@master
      with:
        ide_path: $HOME/arduino-ide
        usr_path: $HOME/Arduino
    - name: Handle Event
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash ./.github/scripts/repository_dispatch.sh
#     - name: Upload build artifacts
#       uses: actions/upload-artifact@v1
#       with:
#         name: artifacts
#         path: build
